### ISSUE TITLE
node v0.13 dependencies

### ISSUE THREAD

**Issue by nicodmf** [wlaurance/slack-for-linux#55] opened 2015-05-18 14:01 UTC
Hello,

With installation process, the bundle want to install:

    http://dl.nwjs.io/v0.13.0/nwjs-v0.13.0-linux-x64.tar.gz

Which is not available as this is an alpha version named nwjs-v0.13.0-alpha0-linux-x64.tar.gz. I'm on debian jessie.

Best Regard,

Nicolas

**Comment by dnh-ee** [comment] 2015-05-18 14:19
Yeah, I'm seeing this issue too... it's actually with downloading nodewebkit: 

Running "nodewebkit:src" (nodewebkit) task
Latest Version: v0.13.0
Using v0.13.0
Create cache folder in ~/.nvm/v0.10.21/lib/node_modules/slack-for-linux/cache/0.13.0
Downloading: http://dl.nwjs.io/v0.13.0/nwjs-v0.13.0-linux-x64.tar.gz
ERROR: The version 0.13.0 does not have a corresponding build posted at http://dl.node-webkit.org/. Please choose a version from that list.

The link only has an alpha version under 0.13.0:
http://dl.nwjs.io/v0.13.0/alpha0/

Have nodewebkit incorrectly updated the latest version to an alpha build?

**Comment by twolfson** [comment] 2015-05-18 18:00
We became aware of the issue in #35. The issue is we were never locking down our `nw.js` version and so the installer is attempting to grab the latest (non-existent) version. There is PR open to repair it in #52.

https://github.com/wlaurance/slack-for-linux/issues/35#issuecomment-101527578

**Comment by dnh-ee** [comment] 2015-05-18 19:40
Ahhh, thanks. I thought I'd seen something that sounded related, but didn't look far enough back.

**Comment by twolfson** [comment] 2015-05-28 17:07
#52 has been landed and published. There were also a few extra PRs to fix up installations (#53, #54). If you install the latest version `1.4.3`, then this issue should be fixed

```bash
npm install -g slack-for-linux@latest
```

**Closed by twolfson** 2015-05-28 17:07 UTC
