### ISSUE TITLE
Unable to upgrade/install

### ISSUE THREAD

**Issue by madmuffin1** [wlaurance/slack-for-linux#44] opened 2015-04-29 16:59 UTC
When I saw the new release I wanted to update right away, so I hacked the usual `sudo npm install -g slack-for-linux` into my console, but somehow this produced an error. I then tried install inside a root shell, and got a different error message. I cannot find the issue. 

Funny enough, at the time of the postinstall script run the folder `/usr/lib/node_modules/slack-for-linux/` does not exist.

Can anyone confirm this problem?

Error case 1 (running `sudo npm`)
    /usr/bin/slack-for-linux -> /usr/lib/node_modules/slack-for-linux/run.js

    > slack-for-linux@1.4.0 postinstall /usr/lib/node_modules/slack-for-linux
    > ./install.sh

    npm ERR! Error: EACCES, mkdir '/usr/lib/node_modules/slack4linux'
    npm ERR!  { [Error: EACCES, mkdir '/usr/lib/node_modules/slack4linux']
    npm ERR!   errno: 3,
    npm ERR!   code: 'EACCES',
    npm ERR!   path: '/usr/lib/node_modules/slack4linux',
    npm ERR!   fstream_type: 'Directory',
    npm ERR!   fstream_path: '/usr/lib/node_modules/slack4linux',
    npm ERR!   fstream_class: 'DirWriter',
    npm ERR!   fstream_stack: 
    npm ERR!    [ '/usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
    npm ERR!      '/usr/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53',
    npm ERR!      'Object.oncomplete (fs.js:107:15)' ] }
    npm ERR! 
    npm ERR! Please try running this command again as root/Administrator.

    npm ERR! System Linux 3.16.0-33-generic
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
    npm ERR! cwd /usr/lib/node_modules/slack-for-linux/app
    npm ERR! node -v v0.10.28
    npm ERR! npm -v 1.4.9
    npm ERR! path /usr/lib/node_modules/slack4linux
    npm ERR! fstream_path /usr/lib/node_modules/slack4linux
    npm ERR! fstream_type Directory
    npm ERR! fstream_class DirWriter
    npm ERR! code EACCES
    npm ERR! errno 3
    npm ERR! stack Error: EACCES, mkdir '/usr/lib/node_modules/slack4linux'
    npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23
    npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
    npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /usr/lib/node_modules/slack-for-linux/app/npm-debug.log
    npm ERR! not ok code 0
    npm ERR! slack-for-linux@1.4.0 postinstall: `./install.sh`
    npm ERR! Exit status 3
    npm ERR! 
    npm ERR! Failed at the slack-for-linux@1.4.0 postinstall script.
    npm ERR! This is most likely a problem with the slack-for-linux package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     ./install.sh
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls slack-for-linux
    npm ERR! There is likely additional logging output above.

    npm ERR! System Linux 3.16.0-33-generic
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "slack-for-linux"
    npm ERR! cwd /home/patrick
    npm ERR! node -v v0.10.28
    npm ERR! npm -v 1.4.9
    npm ERR! code ELIFECYCLE
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/patrick/npm-debug.log
    npm ERR! not ok code 0

Error message 2 (when running npm in a root shell)
    /usr/bin/slack-for-linux -> /usr/lib/node_modules/slack-for-linux/run.js

    > slack-for-linux@1.4.0 postinstall /usr/lib/node_modules/slack-for-linux
    > ./install.sh

    npm ERR! Error: Attempt to unlock ., which hasn't been locked
    npm ERR!     at unlock (/usr/lib/node_modules/npm/lib/cache.js:1434:11)
    npm ERR!     at cb (/usr/lib/node_modules/npm/lib/cache.js:925:5)
    npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:942:20
    npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:1412:20
    npm ERR!     at afterMkdir (/usr/lib/node_modules/npm/lib/cache.js:1085:14)
    npm ERR!     at /usr/lib/node_modules/npm/node_modules/mkdirp/index.js:37:53
    npm ERR!     at Object.oncomplete (fs.js:107:15)
    npm ERR! If you need help, you may report this *entire* log,
    npm ERR! including the npm and node versions, at:
    npm ERR!     <http://github.com/npm/npm/issues>

    npm ERR! System Linux 3.16.0-33-generic
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
    npm ERR! cwd /usr/lib/node_modules/slack-for-linux/app
    npm ERR! node -v v0.10.28
    npm ERR! npm -v 1.4.9
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /usr/lib/node_modules/slack-for-linux/app/npm-debug.log
    npm ERR! not ok code 0
    npm ERR! slack-for-linux@1.4.0 postinstall: `./install.sh`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the slack-for-linux@1.4.0 postinstall script.
    npm ERR! This is most likely a problem with the slack-for-linux package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     ./install.sh
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls slack-for-linux
    npm ERR! There is likely additional logging output above.

    npm ERR! System Linux 3.16.0-33-generic
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "slack-for-linux"
    npm ERR! cwd /home/patrick
    npm ERR! node -v v0.10.28
    npm ERR! npm -v 1.4.9
    npm ERR! code ELIFECYCLE
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /home/patrick/npm-debug.log
    npm ERR! not ok code 0

**Comment by twolfson** [comment] 2015-04-29 20:36
Strange, the first command should work. Although, you are missing an `@latest`. Can you try it again?

```bash
npm install -g slack-for-linux@latest
```

Additionally, it's strongly recommended to avoid using `sudo` with `node_modules`:

https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by madmuffin1** [comment] 2015-04-29 20:49
twolfson, thanks for your response. I just tried upgrading node and npm to the latest versions and added the `@latest` to the install , but an error remains, though it is a different one this time:

    ➜  ~  sudo npm install slack-for-linux@latest -g


    npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
    /usr/bin/slack-for-linux -> /usr/lib/node_modules/slack-for-linux/run.js

    > slack-for-linux@1.4.0 postinstall /usr/lib/node_modules/slack-for-linux
    > ./install.sh

    npm ERR! addLocal Could not install /usr/lib/node_modules/slack-for-linux/app
    npm ERR! Linux 3.16.0-34-generic
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
    npm ERR! node v0.12.2
    npm ERR! npm  v2.7.4
    npm ERR! path /home/patrick/.npm/slack4linux/0.0.1/package.tgz
    npm ERR! code EPERM
    npm ERR! errno -1

    npm ERR! Error: EPERM, chown '/home/patrick/.npm/slack4linux/0.0.1/package.tgz'
    npm ERR!     at Error (native)
    npm ERR!  { [Error: EPERM, chown '/home/patrick/.npm/slack4linux/0.0.1/package.tgz']
    npm ERR!   errno: -1,
    npm ERR!   code: 'EPERM',
    npm ERR!   path: '/home/patrick/.npm/slack4linux/0.0.1/package.tgz' }
    npm ERR! 
    npm ERR! Please try running this command again as root/Administrator.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /usr/lib/node_modules/slack-for-linux/app/npm-debug.log
    npm ERR! Linux 3.16.0-34-generic
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "slack-for-linux@latest" "-g"
    npm ERR! node v0.12.2
    npm ERR! npm  v2.7.4
    npm ERR! code ELIFECYCLE

    npm ERR! slack-for-linux@1.4.0 postinstall: `./install.sh`
    npm ERR! Exit status 255
    npm ERR! 
    npm ERR! Failed at the slack-for-linux@1.4.0 postinstall script './install.sh'.
    npm ERR! This is most likely a problem with the slack-for-linux package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     ./install.sh
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls slack-for-linux
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/patrick/npm-debug.log

Using npm with sudo has not been a problem yet, I only use sudo when installing packages globally.
Also, adding a user writeable folder to the PATH is not really what I want from a security perspective. Especially the way described in the documentation exposes every user at risk since the user-writeable folder added to the PATH is not appended but prepended to the existing path. So an attacker could just drop a very simple script `google-chrome` in there which could potentially start a keylogger in the background and then the real chrome. So this approach completely undermines one of the key security priniciples of the Unix ecosystem!

I might quickly set up a vm to check if that could fix the problem, but that would take a couple of days, as I will go on holiday tomorrow.

**Comment by madmuffin1** [comment] 2015-04-29 20:54
One thing I just realized is that it is trying to find the files of the package in 

`/home/patrick/.npm/slack4linux/0.0.1/package.tgz`

although IMHO the correct path would be

`/home/patrick/.npm/slack4linux/1.4.0/package.tgz`

the path containing the correct version number exists, the other one does not.

**Comment by twolfson** [comment] 2015-04-29 20:58
The counterpoint to that is you are already running arbitrary scripts from the internet under `sudo` rights when you install something globally =/

I am currently distracted by other things at the moment to read further into your error message but will take a look by the end of the weekend.

**Comment by twolfson** [comment] 2015-04-30 06:05
`slack4linux` was used by the `package.json` in our `app/` directory. I am not entirely sure why there would be tarball for it though. Can you post the entire `npm-debug.log` to a gist?

**Comment by twolfson** [comment] 2015-04-30 07:07
While debugging #43 I think I found the cause of the problem. `npm` is attempting to treat our `nw` application as a separate global `npm install` which is leading to permissioning issues. We have introduced #45 to fix this. Hopefully when that lands, this should be patched. Sorry for the inconvenience.

**Comment by madmuffin1** [comment] 2015-04-30 08:41
Cool, thanks a lot. I'll wait for #45 to be merged and will check again.

**Comment by Mte90** [comment] 2015-05-05 13:23
```-
/usr/local/bin/slack-for-linux -> /usr/local/lib/node_modules/slack-for-linux/run.js

> slack-for-linux@1.4.0 postinstall /usr/local/lib/node_modules/slack-for-linux
> ./install.sh

npm ERR! Error: Attempt to unlock ., which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/share/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:22:20
npm ERR!     at /usr/share/npm/node_modules/inflight/inflight.js:22:7
npm ERR!     at Array.forEach (native)
npm ERR!     at res (/usr/share/npm/node_modules/inflight/inflight.js:21:9)
npm ERR!     at /usr/lib/nodejs/once.js:17:15
npm ERR!     at afterMkdir (/usr/share/npm/lib/cache/get-stat.js:53:14)
npm ERR!     at /usr/lib/nodejs/mkdirp/index.js:46:53
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.17-4.towo-siduction-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /usr/local/lib/node_modules/slack-for-linux/app
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lib/node_modules/slack-for-linux/app/npm-debug.log
npm ERR! not ok code 0
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian                                                                                                                                         
 
npm ERR! slack-for-linux@1.4.0 postinstall: `./install.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the slack-for-linux@1.4.0 postinstall script.
npm ERR! This is most likely a problem with the slack-for-linux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./install.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls slack-for-linux
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.17-4.towo-siduction-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "slack-for-linux" "-g"
npm ERR! cwd /var/log/apache2
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/log/apache2/npm-debug.log
npm ERR! not ok code 0
```
Problem confirmed

**Comment by twolfson** [comment] 2015-05-05 22:50
@madmuffin1 #45 has been landed. Can you try installing the latest version again?

**Comment by twolfson** [comment] 2015-05-05 22:52
@Mte90 It sounds like there are locking issues in your install. Were there any error messages earlier in your installation and can you install any other modules globally (e.g. `grunt-cli`)?

**Comment by Mte90** [comment] 2015-05-06 08:25
With other package i've no problem. Now i get a different error:

```
/usr/local/bin/slack-for-linux -> /usr/local/lib/node_modules/slack-for-linux/run.js

> slack-for-linux@1.4.1 postinstall /usr/local/lib/node_modules/slack-for-linux
> ./install.sh

+ npm_config_global=
+ cd app/
+ npm install
npm WARN package.json slack-for-linux@0.0.1 No description
npm WARN package.json slack-for-linux@0.0.1 No repository field.
npm WARN package.json slack-for-linux@0.0.1 No README data
npm ERR! Error: Attempt to unlock get-uri@^0.1.3, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-named.js:32:5)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:41:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:22:20
npm ERR!     at /usr/share/npm/node_modules/inflight/inflight.js:22:7
npm ERR!     at Array.forEach (native)
npm ERR!     at res (/usr/share/npm/node_modules/inflight/inflight.js:21:9)
npm ERR!     at /usr/lib/nodejs/once.js:17:15
npm ERR!     at afterMkdir (/usr/share/npm/lib/cache/get-stat.js:53:14)
npm ERR!     at /usr/lib/nodejs/mkdirp/index.js:46:53
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.17-4.towo-siduction-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /usr/local/lib/node_modules/slack-for-linux/app
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lib/node_modules/slack-for-linux/app/npm-debug.log
npm ERR! not ok code 0
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian                                                                                                                                         
 
npm ERR! slack-for-linux@1.4.1 postinstall: `./install.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the slack-for-linux@1.4.1 postinstall script.
npm ERR! This is most likely a problem with the slack-for-linux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./install.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls slack-for-linux
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.17-4.towo-siduction-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "slack-for-linux"
npm ERR! cwd /home/mte90
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mte90/npm-debug.log
npm ERR! not ok code 0
```
I have npm 1.4.21+ds-2 and nodejs v0.10.29 on debian, the get-uri@^0.1.3 package is installed.

**Comment by madmuffin1** [comment] 2015-05-06 10:20
Since the patch was merged in yesterday, I gave it a shot but unfortunately, it still does not work.
What is interesting, is that the version tag (just like in @Mte90 s post), the version tag is 0.0.1

I'll post a complete error log later.

**Comment by twolfson** [comment] 2015-05-06 19:55
Ugh, this is probably my bad. While I have tested via an install from a `git` URL. I have not checked the `1.4.1` published version yet. I will check by the end of this weekend.

**Comment by madmuffin1** [comment] 2015-05-06 19:57
Can you just quickly paste the command I have to type to test it against the latest git version?

**Comment by twolfson** [comment] 2015-05-06 20:03
Yea, `npm` supports `git+ssh` URLs as simplified GitHub URLs and ref's via a `#` delimiter. For the landed PR, it was:

```bash
npm install -g twolfson/slack-for-linux#bc50c974ddbf756a4fccb96f0190a87072543035

# If that doesn't work, the full form is:
npm install -g git+ssh://git@github.com:twolfson/slack-for-linux#bc50c974ddbf756a4fccb96f0190a87072543035
```

**Comment by madmuffin1** [comment] 2015-05-06 20:13
The problem remains with the version pulled directly from git. If you had a hint for me where to start looking, i'll gladly look into it, but I have no experience with the npm install process

**Comment by twolfson** [comment] 2015-05-06 20:21
Sure thing, the algorithm in prose form is written up here:

https://docs.npmjs.com/cli/install#algorithm

The `--verbose` output usually helps to debug what `npm` is thinking (very detailed). If you can't figure it out, please upload the latest output from your install script.

@Mte90 I am going to hold up on to see if @madmuffin1 can patch it or not before looking into your issue. I have a feeling you have the same scenarios.

**Comment by vkhazin** [comment] 2015-05-08 16:02
/usr/bin/slack-for-linux -> /usr/lib/node_modules/slack-for-linux/run.js

> slack-for-linux@1.4.1 postinstall /usr/lib/node_modules/slack-for-linux
> ./install.sh

+ npm_config_global=
+ cd app/
+ npm install
npm WARN package.json slack-for-linux@0.0.1 No description
npm WARN package.json slack-for-linux@0.0.1 No repository field.
npm WARN package.json slack-for-linux@0.0.1 No README data
underscore@1.8.3 node_modules/underscore

get-uri@0.1.3 node_modules/get-uri
├── extend@1.2.1
├── file-uri-to-path@0.0.2
├── debug@0.8.1
├── data-uri-to-buffer@0.0.3
├── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
└── ftp@0.3.10 (xregexp@2.0.0, readable-stream@1.1.13)
+ ../node_modules/.bin/bower install
bower                           EACCES EACCES, permission denied '/home/vkhazin/.cache/bower/registry/bower.herokuapp.com/lookup'

Stack trace:
Error: EACCES, permission denied '/home/vkhazin/.cache/bower/registry/bower.herokuapp.com/lookup'
    at Object.fs.mkdirSync (fs.js:654:18)
    at Function.sync (/usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/bower-registry-client/node_modules/mkdirp/index.js:55:12)
    at new Cache (/usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/bower-registry-client/lib/util/Cache.js:21:16)
    at RegistryClient.<anonymous> (/usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/bower-registry-client/lib/lookup.js:163:35)
    at Array.forEach (native)
    at RegistryClient.initCache (/usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/bower-registry-client/lib/lookup.js:150:34)
    at RegistryClient._initCache (/usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/bower-registry-client/Client.js:62:27)
    at new RegistryClient (/usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/bower-registry-client/Client.js:16:10)
    at new PackageRepository (/usr/lib/node_modules/slack-for-linux/node_modules/bower/lib/core/PackageRepository.js:17:28)
    at new Manager (/usr/lib/node_modules/slack-for-linux/node_modules/bower/lib/core/Manager.js:17:24)

Console trace:
Error
    at StandardRenderer.error (/usr/lib/node_modules/slack-for-linux/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/usr/lib/node_modules/slack-for-linux/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/slack-for-linux/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/q/q.js:830:24)
    at /usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/q/q.js:856:30
    at Promise.when (/usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/q/q.js:1108:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/q/q.js:774:41)
    at /usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/q/q.js:542:49
System info:
Bower version: 1.4.1
Node version: 0.10.38
OS: Linux 3.13.0-49-generic x64
npm ERR! Linux 3.13.0-49-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "slack-for-linux" "-g"
npm ERR! node v0.10.38
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE

**Comment by twolfson** [comment] 2015-05-14 04:45
@madmuffin1 It has been a week and we are receiving other issues about this. I am going to take a look at reproducing in a Vagrant environment.

**Comment by twolfson** [comment] 2015-05-14 04:54
I have encountered an error but it is neither of the ones you folks have posted:

https://gist.github.com/twolfson/bce148ecba3391ba940f

```
npm verb exit [ 0, true ]
npm info ok 
+ ../node_modules/.bin/bower install

Error: EACCES, permission denied '/home/vagrant/.config'
    at Object.fs.mkdirSync (fs.js:654:18)
    at sync (/usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/mkdirp/index.js:70:13)
    at Function.sync (/usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/mkdirp/index.js:76:24)
    at Object.create.all.get (/usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/configstore/index.js:41:13)
    at Object.Configstore (/usr/lib/node_modules/slack-for-linux/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/usr/lib/node_modules/slack-for-linux/node_modules/bower/lib/config.js:22:23)
    at defaultConfig (/usr/lib/node_modules/slack-for-linux/node_modules/bower/lib/config.js:11:24)
    at Object.<anonymous> (/usr/lib/node_modules/slack-for-linux/node_modules/bower/lib/index.js:40:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

npm verb unsafe-perm in lifecycle false
npm info slack-for-linux@1.4.1 Failed to exec postinstall script
npm ERR! slack-for-linux@1.4.1 postinstall: `./install.sh`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the slack-for-linux@1.4.1 postinstall script.
npm ERR! This is most likely a problem with the slack-for-linux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./install.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls slack-for-linux
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-43-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "slack-for-linux" "-g" "--verbose"
npm ERR! cwd /home/vagrant
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm verb exit [ 1, true ]
npm verb lib/node_modules/slack-for-linux unbuild
npm info preuninstall slack-for-linux@1.4.1
npm info uninstall slack-for-linux@1.4.1
npm verb true,/usr/lib/node_modules,/usr/lib/node_modules unbuild slack-for-linux@1.4.1
npm verb /usr/bin,[object Object] binRoot
npm info postuninstall slack-for-linux@1.4.1
npm ERR! not ok code 0
```

**Comment by twolfson** [comment] 2015-05-14 05:43
I have gotten `slack-for-linux` running inside of an Ubuntu 14.04 Vagrant machine. I wound up removing bower due to permissioning issues with root and home directories. I have a feeling that this issue's problem isn't patched so can you please try out the flavor on the PR:

```bash
npm install -g twolfson/slack-for-linux#826f1ba
```

**Comment by twolfson** [comment] 2015-05-14 06:20
I ran into more errors when following the steps in #47. After a lot of thought, I realized that we should not be building the package on the machine as the build is always consistent (`nw.js@0.12` and `linux64`). As a result, I am going to propose via a PR to publish a built version to `npm`. As a sample, you can use a built version via this install:

```bash
npm install -g twolfson/slack-for-linux#8089b60
```

**Comment by Mte90** [comment] 2015-05-14 08:44
I get this 
```
FATAL ERROR: JS Allocation failed - process out of memory
```

**Comment by twolfson** [comment] 2015-05-14 16:43
Strange, `npm` should be buffering to disk on download. Can you run the install with a `--verbose` and upload the output to a gist?

**Comment by madmuffin1** [comment] 2015-05-17 17:38
Sorry, it's been a hectic week and I went on a weekend trip. I just tried to install the changeset 8089b60 from your repository and it installs without errors (verbose output at https://gist.github.com/madmuffin1/6a64e66172c12dcea070), but when I try to run it, it errors:

    ➜  ~  slack-for-linux                                                                                              
    events.js:85
          throw er; // Unhandled 'error' event
            ^
    Error: spawn /usr/lib/node_modules/slack-for-linux/./webkitbuilds/slack-for-linux/linux64/slack-for-linux ENOENT
        at exports._errnoException (util.js:746:11)
        at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
        at child_process.js:1144:20
        at process._tickCallback (node.js:355:11)
        at Function.Module.runMain (module.js:503:11)
        at startup (node.js:129:16)
        at node.js:814:3

I checked `/usr/lib/node_modules/slack-for-linux/` and it does not contain a `webkitbuilds` folder. Any clues?

**Comment by madmuffin1** [comment] 2015-05-17 18:36
Oh shoot, downgrading to 1.2.1 also fails now, since the latest version of node-webkit does not have a release version.

**Comment by twolfson** [comment] 2015-05-17 18:40
Damn, no idea why it's not showing up in `git`. Over the weekend, I realized there is another strategy that I have used with other `nw.js`/Electron projects; install all dependencies via the main `package.json`. Going to try that out later.

As for the 1.2.1 issue, I will whip up a quick branch for you to use to get the fixes for `nw.js` version locking against 1.2.1

https://github.com/wlaurance/slack-for-linux/pull/49

**Comment by twolfson** [comment] 2015-05-17 18:43
@madmuffin1 `feab05c` should work as a patched 1.2.1 for now:

```bash
npm install -g twolfson/slack-for-linux#feab05c
```

**Comment by twolfson** [comment] 2015-05-17 20:10
@madmuffin1 I think we finally solved the permissioning issue in #54. Can you try it out?

```bash
npm install -g twolfson/slack-for-linux#0189e8e
```

**Comment by madmuffin1** [comment] 2015-05-17 20:48
feab05c works like a charm, thanks for the quickfix!

for 0189e8e: it still installs fine, but references a `nw` executable that is not included in the package and does not exist on my system. Am I supposed to install it manually from nwjs.io?

stderr when running `slack-for-linux`:
    events.js:85
          throw er; // Unhandled 'error' event
            ^
    Error: spawn nw ENOENT
        at exports._errnoException (util.js:746:11)
        at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
        at child_process.js:1144:20
        at process._tickCallback (node.js:355:11)
        at Function.Module.runMain (module.js:503:11)
        at startup (node.js:129:16)
        at node.js:814:3

**Comment by madmuffin1** [comment] 2015-05-17 20:53
Oh, so I installed (`npm install -g nw`) a nw executable - but now when I run slack-for-linux I get this screen: 

![cannot run package_063](https://cloud.githubusercontent.com/assets/1918026/7672135/86515a8a-fce7-11e4-96f2-181a4beca976.png)

**Comment by madmuffin1** [comment] 2015-05-17 21:00
So I looked into the package, and it includes a dependency on nw, but it tries to start up a globally installed one. So I changed line 6 of run.js to

    spawn('./node_modules/nw/bin/nw', ['.'], {stdio: [0, 1, 2]});

and voila: it starts up! :+1:

**Comment by twolfson** [comment] 2015-05-18 01:39
Glad to hear that it's finally working =) I think I assumed `bin` scripts would have the `.bin` executables from their own node modules but I guess I was wrong. I will update the PR to reflect your changes.

**Comment by twolfson** [comment] 2015-05-28 17:06
#54 has been landed in `1.4.3`. If you install the latest, then it should upgrade/install without issue :tada: 

```bash
npm install -g slack-for-linux@latest
```

**Closed by twolfson** 2015-05-28 17:06 UTC

**Comment by Mte90** [comment] 2015-05-28 19:59
I get this :-/
```
root@siduction:/home/mte90# npm install -g slack-for-linux@latest
-
> nw@0.12.1 postinstall /usr/local/lib/node_modules/slack-for-linux/node_modules/nw
> node scripts/install.js

ENOSPC, write
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian                                                                                                                                         
 
npm ERR! nw@0.12.1 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nw@0.12.1 postinstall script.
npm ERR! This is most likely a problem with the nw package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls nw
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.17-4.towo-siduction-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "slack-for-linux@latest"
npm ERR! cwd /home/mte90
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mte90/npm-debug.log
npm ERR! not ok code 0
root@siduction:/home/mte90# npm install -g nw
/usr/local/bin/nw -> /usr/local/lib/node_modules/nw/bin/nw

> nw@0.12.2 postinstall /usr/local/lib/node_modules/nw
> node scripts/install.js

ENOSPC, write
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian                                                                                                                                         
 
npm ERR! nw@0.12.2 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nw@0.12.2 postinstall script.
npm ERR! This is most likely a problem with the nw package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls nw
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.17-4.towo-siduction-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "nw"
npm ERR! cwd /home/mte90
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mte90/npm-debug.log
npm ERR! not ok code 0
```

**Comment by madmuffin1** [comment] 2015-05-28 20:24
@Mte90 As you are still on node 0.10 on debian (the error also states this might be causing some issues), you could try upgrading to latest node using the steps described here: https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories

In short:

    # Note the new setup script name for Node.js v0.12
    curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
    
    # Then install with:
    sudo apt-get install -y nodejs

**Comment by Mte90** [comment] 2015-05-28 20:46
Ok now the installation works without problems :-)

**Comment by twolfson** [comment] 2015-05-28 20:57
Weird, I am surprised that `node@0.10` was the issue for an `ENOSPC`. That typically reflects no space available on disk. Glad to hear it's all working now though. Thanks @madmuffin1 for the quick reply! =)
