### ISSUE TITLE
Unable to install - Linux mint LMDE

### ISSUE THREAD

**Issue by AntoineLemaire** [wlaurance/slack-for-linux#47] opened 2015-05-07 08:31 UTC
I run all commands in root shell, and already did `npm install npm@latest -g`

	antoine-pc1# npm install slack-for-linux -g
	/usr/local/bin/slack-for-linux -> /usr/local/lib/node_modules/slack-for-linux/run.js

	> slack-for-linux@1.4.1 postinstall /usr/local/lib/node_modules/slack-for-linux
	> ./install.sh

	+ npm_config_global=
	+ cd app/
	+ npm install
	npm WARN package.json slack-for-linux@0.0.1 No description
	npm WARN package.json slack-for-linux@0.0.1 No repository field.
	npm WARN package.json slack-for-linux@0.0.1 No README data
	npm ERR! Linux 3.11-2-amd64
	npm ERR! argv "node" "/usr/local/bin/npm" "install"
	npm ERR! node v0.10.31
	npm ERR! npm  v2.9.0
	npm ERR! path /root/.npm/underscore/1.8.3/package
	npm ERR! code EACCES
	npm ERR! errno 3

	npm ERR! Error: EACCES, mkdir '/root/.npm/underscore/1.8.3/package'
	npm ERR!  { [Error: EACCES, mkdir '/root/.npm/underscore/1.8.3/package']
	npm ERR!   errno: 3,
	npm ERR!   code: 'EACCES',
	npm ERR!   path: '/root/.npm/underscore/1.8.3/package',
	npm ERR!   parent: 'slack-for-linux' }
	npm ERR! 
	npm ERR! Please try running this command again as root/Administrator.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /usr/local/lib/node_modules/slack-for-linux/app/npm-debug.log
	npm ERR! Linux 3.11-2-amd64
	npm ERR! argv "node" "/usr/local/bin/npm" "install" "slack-for-linux" "-g"
	npm ERR! node v0.10.31
	npm ERR! npm  v2.9.0
	npm ERR! code ELIFECYCLE

	npm ERR! slack-for-linux@1.4.1 postinstall: `./install.sh`
	npm ERR! Exit status 3
	npm ERR! 
	npm ERR! Failed at the slack-for-linux@1.4.1 postinstall script './install.sh'.
	npm ERR! This is most likely a problem with the slack-for-linux package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     ./install.sh
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls slack-for-linux
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /home/antoine/npm-debug.log

**Comment by twolfson** [comment] 2015-05-07 16:40
Is there any reason for installing via a root shell? Have you tried installing via a `sudo npm install` previously?

**Comment by AntoineLemaire** [comment] 2015-05-11 09:31
No reason, just habits.
But the problem is exactly the same with sudo

**Comment by twolfson** [comment] 2015-05-12 07:14
Darn =( This is probably the same issue as in #44. I am letting @madmuffin1 take a look at that one first. I am going to leave this open as well since I have no conclusive evidence if they are/aren't (the log seems to be different).

**Comment by twolfson** [comment] 2015-05-14 05:45
I have taken an attempt to reproduce on a Vagrant machine for #44. I ran into something different but it might fix your issue. Can you please try installing this version?

```bash
npm install -g twolfson/slack-for-linux#826f1ba
```

**Comment by twolfson** [comment] 2015-05-14 06:21
Actually, never mind. I attempted to reproduce as root and ran into more issues. However, I am realizing that building on the machine is difficult and doesn't allow for reuse in `.deb`/`.rpm`. In order to fix this, I am going to suggest we start publishing built versions to `npm`.

You can find a preview version that has a compiled version here:

```bash
npm install -g twolfson/slack-for-linux#8089b60
```

**Comment by twolfson** [comment] 2015-05-17 20:09
I have worked out a better solution than including the bundled files. We are bundling our installs to remove these multiple permissioning issues. Please try out:

```bash
npm install -g twolfson/slack-for-linux#0189e8e
```

**Comment by AntoineLemaire** [comment] 2015-05-18 07:52
It seems I can't :/

```
npm ERR! git rev-list -n1 0189e8e: fatal: ambiguous argument '0189e8e': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 0189e8e: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 0189e8e: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 0189e8e: 
npm ERR! git rev-list -n1 0189e8e: fatal: ambiguous argument '0189e8e': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 0189e8e: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 0189e8e: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 0189e8e: 
npm ERR! git rev-list -n1 0189e8e: fatal: ambiguous argument '0189e8e': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 0189e8e: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 0189e8e: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 0189e8e: 
npm ERR! Linux 3.11-2-amd64
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "twolfson/slack-for-linux#0189e8e"
npm ERR! node v0.10.31
npm ERR! npm  v2.9.0
npm ERR! code 128

npm ERR! Command failed: fatal: ambiguous argument '0189e8e': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/antoine/npm-debug.log
```

**Comment by madmuffin1** [comment] 2015-05-18 07:59
@AntoineLemaire thats right, twolfson always squishes his commits, so after he added another fix, the revision is not in the tree any more. you should be able to try out 

    npm install -g twolfson/slack-for-linux#237828b

which is an further improved changeset of the 0189e8e or use

    npm install -g twolfson/slack-for-linux#ae24fe4

which is the un-squished version

**Comment by AntoineLemaire** [comment] 2015-05-18 08:06
Thanks, where can I see lasted commits ? There's nothing on master 

Install complete well, but slack doesn't start
```

antoine-pc1 :: ~ » sudo npm install -g twolfson/slack-for-linux#237828b                                                                                                                                                                  1 ↵
\
> nw@0.12.1 postinstall /usr/local/lib/node_modules/slack-for-linux/node_modules/nw
> node scripts/install.js

/usr/local/bin/slack-for-linux -> /usr/local/lib/node_modules/slack-for-linux/run.js
slack-for-linux@1.4.1 /usr/local/lib/node_modules/slack-for-linux
├── underscore@1.8.3
├── favico.js@0.3.8
├── get-uri@0.1.3 (extend@1.2.1, file-uri-to-path@0.0.2, data-uri-to-buffer@0.0.3, debug@0.8.1, readable-stream@1.0.33, ftp@0.3.10)
└── nw@0.12.1 (file-exists@0.1.1, merge@1.2.0, semver@4.3.4, chalk@1.0.0, multimeter@0.1.1, rimraf@2.3.3, yargs@3.9.0, decompress@2.3.0, download@3.3.0)



antoine-pc1 :: ~ » slack-for-linux

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```

(Same issue with sudo)

**Comment by madmuffin1** [comment] 2015-05-18 08:07
The working tree of the fix twolfson is trying to implement is at https://github.com/twolfson/slack-for-linux/tree/dev/single.install.sqwished

**Comment by AntoineLemaire** [comment] 2015-05-18 08:10
Oh right, I didn't see the change of repo ! Sorry :D

**Comment by twolfson** [comment] 2015-05-18 18:08
Thanks for helping out @madmuffin1 =)

ENOENT occurs when a file (or executable in this case) cannot be resolved. It looks like I missed out on using the proper directories for the script. I have added a `cwd` declaration to patch it:

```
npm install -g twolfson/slack-for-linux#6a99eb6050e3e97b79a44cc0df1c56c04c2ca4dc
```

https://github.com/twolfson/slack-for-linux/commit/6a99eb6050e3e97b79a44cc0df1c56c04c2ca4dc

https://github.com/wlaurance/slack-for-linux/compare/master...twolfson:dev/single.install

**Comment by AntoineLemaire** [comment] 2015-05-19 19:57
It's working well thanks ! :+1:

**Comment by twolfson** [comment] 2015-05-19 20:02
Woo hoo! That's great to hear =)

**Comment by wlaurance** [comment] 2015-05-28 15:36
Also related to #54 which has been landed and published.

**Closed by wlaurance** 2015-05-28 15:36 UTC
